Add a Playground so you can play with Promises interactively
khanlou/Promise pull request #2
Opened 2016-09-10 19:07 UTC by kelan

Changes to the Promise code:
* Add `public` to everything so it's accessible from outside the module.
* Add some headerdoc (mostly copy/pasted from http://khanlou.com/2016/08/common-patterns-with-promises/)

2016-09-10 19:11 UTC, kelan commented
I've been playing with this project recently in a Playground, and thought it was a good example for including the playground with the project, as I talk about [here](http://kelan.io/2016/playgrounds-for-libraries/).

2016-09-14 22:28 UTC, khanlou commented on Promise.playground/Pages/Basic Usage.xcplaygroundpage/Contents.swift
> +}
i know i haven't published a style guide yet, but i'm not using trailing block syntax for this project. i'll comment each time it needs to be fixed

2016-09-14 22:28 UTC, khanlou commented on Promise.playground/Pages/Common Patterns.xcplaygroundpage/Contents.swift
> +    }
trailing block syntax

2016-09-14 22:28 UTC, khanlou commented on Promise.playground/Pages/Common Patterns.xcplaygroundpage/Contents.swift
> +    }
trailing block syntax

2016-09-14 22:28 UTC, khanlou commented on Promise.playground/Pages/Common Patterns.xcplaygroundpage/Contents.swift
> +    }
trailing block syntax

2016-09-14 22:29 UTC, khanlou commented on Promise.playground/Pages/Common Patterns.xcplaygroundpage/Contents.swift
> +    }
trailing block syntax

2016-09-14 22:29 UTC, khanlou commented on Promise.playground/Pages/Common Patterns.xcplaygroundpage/Contents.swift
> +}
trailing block syntax, and also you can use the `work:` initializer instead of `dispatch_async`

2016-09-14 22:29 UTC, khanlou commented on Promise.playground/Pages/Common Patterns.xcplaygroundpage/Contents.swift
> +    }
trailing block syntax

2016-09-14 22:30 UTC, khanlou commented on Promise.playground/Pages/Common Patterns.xcplaygroundpage/Contents.swift
> +    }
trailing block syntax

2016-09-14 22:30 UTC, khanlou commented on Promise/Promise+Extras.swift
> +    public static func all<T>(promises: [Promise<T>]) -> Promise<[T]> {
are  these comments formatted such that they show up when the user option-clicks?

2016-09-14 22:31 UTC, khanlou requested changes

2016-09-15 00:25 UTC, kelan commented on Promise/Promise+Extras.swift
> +    public static func all<T>(promises: [Promise<T>]) -> Promise<[T]> {
Yeah, it's standard headerdoc for Swift code, and shows up when you option-click on the symbol in Xcode.

2016-09-15 00:26 UTC, kelan commented
Thanks for the feedback!  I'll try to work on the style tweaks later tonight.

2016-09-15 01:51 UTC, kelan commented on Promise.playground/Pages/Common Patterns.xcplaygroundpage/Contents.swift
> +}
> also you can use the work: initializer
Oh, right.

2016-09-15 01:55 UTC, kelan commented
I think I got 'em all.

2016-09-15 02:27 UTC, khanlou commented on Promise/Promise+Extras.swift
> +    public static func all<T>(promises: [Promise<T>]) -> Promise<[T]> {
sweet!

2016-09-15 02:34 UTC, khanlou approved these changes

2016-09-15 02:34 UTC, merged